
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE='django_db'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='password'
      - MYSQL_ROOT_PASSWORD='password'
      - MYSQL_HOST=''
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
