
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app
  django_app:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: "django_cont"
    ports:
      - "8001:8001"
    command: gunicorn core.wsgi --bind 0.0.0.0:8001
    env_file:
      - "./django/.env"
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db_cont"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data/mysql/db:/var/lib/mysql
