
services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3307
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  web:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/usr/src/Backend/
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db